### ISSUE TITLE
SS4 branch

### ISSUE THREAD

**Issue by adrian-stein** [silverstripe/silverstripe-multiuser-editing-alert#10]
Are you going to make an SS4 branch for this repo?

**Comment by dhensby** [comment]
This probably won't happen until someone decides to open a PR adding 4.x support, then we can look at getting the branches set up nicely

**Comment by adrian-stein** [comment]
Please see https://github.com/silverstripe/silverstripe-multiuser-editing-alert/pull/11

**Comment by robbieaverill** [comment]
Thanks for doing this @adrian-stein
