### ISSUE TITLE
Silverstripe 4.1 - SVG paths

### ISSUE THREAD

**Issue by aletail** [silverstripe/silverstripe-multiuser-editing-alert#14]
The svg images paths are missing the "vendor" folder, so the images are boken in the CMS.

![svg-images-broken](https://user-images.githubusercontent.com/3344301/39591046-8ab6f7c2-4ed0-11e8-9ebb-dc003febdb50.jpg)

I opened a pull request #15

**Comment by purplespider** [comment]
Had the same issue and this PR resolved it. Can it be merged?
