### ISSUE TITLE
Please tag the the SVG path resolution

### ISSUE THREAD

**Issue by MrJamesEllis** [silverstripe/silverstripe-multiuser-editing-alert#17]
Hi

Could you please tag the change adding "vendor" to the SVG paths in master @ https://github.com/silverstripe/silverstripe-multiuser-editing-alert/commit/1be74a23c9c060d13bf1ed5e2da6a81a117ed010#diff-fac4cdfd4096f52540df16ed2c97b684

I'm using v2.0 in an SS4.1 project with a public/ directory on a project and the paths aren't resolving.

This may affect people using ~2.0 without a public directory so maybe a 3.0 tag is needed?

Thanks
James

**Comment by tardinha** [comment]
Seconded!

**Comment by UndefinedOffset** [comment]
@dhensby any update on this?

**Comment by dhensby** [comment]
Done 2.0.1

**Comment by UndefinedOffset** [comment]
@dhensby Thanks for that :) however looks like Packagist may not be updating automatically see https://packagist.org/packages/silverstripe/multiuser-editing-alert

**Comment by dhensby** [comment]
@candidasa - it seems you're the only admin on packagist for this - can you add me, please?

**Comment by candidasa** [comment]
@dhensby Done.

**Comment by dhensby** [comment]
@UndefinedOffset all updated on packagist
