### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by RoyalPulp** [silverstripe/silverstripe-multiuser-editing-alert#21]
Hey, 
I just tried, if a silverstripe project runs on php 8.1, got a "Server Error" in the Backend , when editing a page:

this is the error-log entry:

PHP Deprecated:  unserialize(): Passing null to parameter #1 ($data) of type string is deprecated in (...)/vendor/silverstripe/multiuser-editing-alert/src/MultiUserEditingController.php on line 37

Have a nice day, 
Hendrik

**Comment by michalkleiner** [comment]
Thanks for the fix @3Dgoo, the change is released as https://github.com/silverstripe/silverstripe-multiuser-editing-alert/releases/tag/2.0.3.
