### ISSUE TITLE
Error being emailed out.

### ISSUE THREAD

**Issue by MattyBalaam** [silverstripe/silverstripe-multiuser-editing-alert#3]
[Error] User needs to be logged in access multi-user editing data
/var/lib/silverstripe/www.neweraed.co.uk.btn.dbplc.com/multiuser-editing/code/MultiUserEditingController.php:20

**Comment by dhensby** [comment]
Someone's trying to access the controller whilst not being logged in

**Comment by MattyBalaam** [comment]
I guess I don't understand why. These errors wouldn't normally be sent out if someone was logged out would they?

**Comment by dhensby** [comment]
the controller is probably having the `init` function run before the `canView` or other security checks are happening.

**Comment by MattyBalaam** [comment]
OK, so are you saying this would not happen on a base install, and another module or some custom code is causing this issue?

**Comment by dhensby** [comment]
From what I see the only way to access this controller is by sending a request to `/admin/editing/$ID`. That URL is called by a JS script that is loaded in the admin area.

The only way I can replicate this error is to login to the admin, then logout in another tab and then the ping hits the server and reveals that error.

I admit it would be nicer just to throw a permissions error and to trigger the login modal in the CMS, but I can't work on that at the moment.
