### ISSUE TITLE
Entire tooltop hoverable when not active.

### ISSUE THREAD

**Issue by MattyBalaam** [silverstripe/silverstripe-multiuser-editing-alert#6]
The entire tooltip blocks access to any UI underneath it when not showing.

The entire hoverable area is highlighted below.

![image](https://cloud.githubusercontent.com/assets/1246923/18958684/56246560-865b-11e6-9120-8dd84edfcad5.png)

Some solutions:

display: none / z-index / height

**Comment by candidasa** [comment]
Thanks for the pull request to correct this
